source 'https://rubygems.org'

gem 'jekyll', '>= 3.6.3'
gem 'jekyll-sitemap'
gem 'octopress', '~> 3.0.0.rc.12'
gem 'rouge'
gem 'ffi', '>= 1.9.24'
gem 'concurrent-ruby', '1.3.5' 
gem 'http_parser.rb', '>= 0.6.0'
gem 'logger'
gem 'csv'
gem 'base64'
gem 'bigdecimal'
gem 'webrick'